baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "cksckrs.github.io" # the base hostname & protocol for your site.
title: "Les Cocksuckers"
description: "Punk Rock'n Roll Festif"
host: 0.0.0.0

paginate: 10 #articles per page
paginate_path: /blog/page:num #makes pagination working

#contacts
git: "https://github.com/cksckrs"  #your github url here.
#stackoverflow: "http://stackoverflow.com/users/1231365/railsr" #Add your stackoverflow url here.
twitter: "https://twitter.com/ccksckrs"  #Add your twitter url here.

#disqus comment
#disqus:
#    shortname: "test" #your disqus comment short name

#google analytics
google:
    tracking-id: "" #your tracking id here

plugins:
  - jekyll-sitemap
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
